services:
  - type: web
    name: jntua-attendance-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USE_SSL
        value: "False"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DATABASE_URL
        sync: false
